name: deploy

on:
  workflow_run:
    workflows: ["python-ci-cd"]
    types:
      - completed

jobs:
    deploy-code:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - name: test
              run: echo "hello world"

